FROM openjdk
MAINTAINER Joshim Ahmed
COPY shakespoke_docker/ /usr/local/bin/shakespoke_docker
WORKDIR /usr/local/bin/shakespoke_docker
ENV CLASSPATH=$CLASSPATH:/usr/local/bin/shakespoke_docker/gson-2.8.6.jar